-- PulseCup schema — Supabase SQL

-- Profiles (maps to wallet or guest session)
create table profiles (
  id text primary key,
  display_name text not null default 'Guest Fan',
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Reactions submitted by a user for a specific event
create table reactions (
  id uuid primary key default gen_random_uuid(),
  profile_id text not null references profiles(id) on delete cascade,
  fixture_id bigint not null,
  event_id text not null,
  reaction_id text not null,
  created_at timestamptz not null default now()
);

create index idx_reactions_fixture on reactions(fixture_id);
create index idx_reactions_profile on reactions(profile_id);

-- Challenges generated by the moment engine from a TxLINE event
create table challenges (
  id text primary key,
  fixture_id bigint not null,
  challenge_type text not null,
  prompt text not null,
  options jsonb not null default '[]',
  status text not null default 'OPEN',
  correct_option_index int,
  trigger_event_id text,
  created_by_event_id text not null,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index idx_challenges_fixture on challenges(fixture_id);

-- User entries (answers) to challenges
create table challenge_entries (
  id uuid primary key default gen_random_uuid(),
  profile_id text not null references profiles(id) on delete cascade,
  challenge_id text not null references challenges(id) on delete cascade,
  selected_option int not null,
  created_at timestamptz not null default now(),
  unique(profile_id, challenge_id)
);

-- Streak snapshots per user per fixture
create table streaks (
  id uuid primary key default gen_random_uuid(),
  profile_id text not null references profiles(id) on delete cascade,
  fixture_id bigint not null,
  current_streak int not null default 0,
  best_streak int not null default 0,
  correct_count int not null default 0,
  total_answered int not null default 0,
  fastest_reaction_ms int,
  mood text not null default 'Casual Fan',
  updated_at timestamptz not null default now(),
  unique(profile_id, fixture_id)
);

-- Recap cards generated after a match
create table recap_cards (
  id text primary key,
  profile_id text not null references profiles(id) on delete cascade,
  fixture_id bigint not null,
  home_team text not null,
  away_team text not null,
  home_score int not null default 0,
  away_score int not null default 0,
  best_streak int not null default 0,
  correct_calls text not null default '0/0',
  fastest_reaction text not null default '—',
  mood text not null default 'Ice Cold',
  total_reactions int not null default 0,
  created_at timestamptz not null default now()
);

create index idx_recaps_profile on recap_cards(profile_id);
create index idx_recaps_fixture on recap_cards(fixture_id);

-- Optional TxLINE event cache (only populated from real TxLINE responses)
create table txline_event_cache (
  id uuid primary key default gen_random_uuid(),
  fixture_id bigint not null,
  txline_sequence int not null,
  event_type text not null,
  raw jsonb not null,
  fetched_at timestamptz not null default now(),
  unique(fixture_id, txline_sequence)
);

create index idx_txline_cache_fixture on txline_event_cache(fixture_id);

-- Enable Row Level Security
alter table profiles enable row level security;
alter table reactions enable row level security;
alter table challenges enable row level security;
alter table challenge_entries enable row level security;
alter table streaks enable row level security;
alter table recap_cards enable row level security;
alter table txline_event_cache enable row level security;

-- RLS: users can only read/write their own data
create policy "Users can read own profile"
  on profiles for select using (id = current_setting('app.profile_id', true)::text);
create policy "Users can upsert own profile"
  on profiles for insert with check (id = current_setting('app.profile_id', true)::text);
create policy "Users can update own profile"
  on profiles for update using (id = current_setting('app.profile_id', true)::text);

create policy "Users can read own reactions"
  on reactions for select using (profile_id = current_setting('app.profile_id', true)::text);
create policy "Users can insert own reactions"
  on reactions for insert with check (profile_id = current_setting('app.profile_id', true)::text);

create policy "Anyone can read challenges"
  on challenges for select using (true);

create policy "Users can read own challenge entries"
  on challenge_entries for select using (profile_id = current_setting('app.profile_id', true)::text);
create policy "Users can insert own challenge entries"
  on challenge_entries for insert with check (profile_id = current_setting('app.profile_id', true)::text);

create policy "Users can read own streaks"
  on streaks for select using (profile_id = current_setting('app.profile_id', true)::text);
create policy "Users can upsert own streaks"
  on streaks for insert with check (profile_id = current_setting('app.profile_id', true)::text);
create policy "Users can update own streaks"
  on streaks for update using (profile_id = current_setting('app.profile_id', true)::text);

create policy "Users can read own recap cards"
  on recap_cards for select using (profile_id = current_setting('app.profile_id', true)::text);
create policy "Users can insert own recap cards"
  on recap_cards for insert with check (profile_id = current_setting('app.profile_id', true)::text);
